package com.example.myapplication.ui.recadapter

import com.example.myapplication.R

data class notif(var image:Int, var title:String, var text:String)
class MyNotif{var list = arrayListOf(notif(R.drawable.ver1, "New promotion techniques", "Techniques which are used to win customers include coupons, samples, money back, competitions etc. Many of these techniques are over a hundred years old. New promotion techniques are not often developed and, even when they are, there is always a risk that they will not please customers. So why do companies still try to develop new promotion techniques? The answer is because companies which do develop a successful new promotion can win many customers because they are the first to use the technique.\n" +
        "\n" +
        "The oil company Shell invented a new 'matching-half' promotion called 'Make Money*. Each time people bought a Shell product they were given half of a bank note. If they got the other half of the note they could get the money for the two halves. So for example, if they got two halves of a 500 soum note, they could get 500 soum in cash in the Shell shop. The competition was very successful because it was simple, it was easy to win and people liked getting cash immediately. Shell liked it because it could control the amount of money it had to pay. It printed a limited number of matching halves. 'Make Money' was a very successful promotion and paid for itself many times over. It helped Shell to increase its sales by 50% over a ten week period. When the promotion was over, sales remained high for several This was because some motorists who had changed to buy Shell products during the promotion continued to buy them after the promotion ended."),
    notif(R.drawable.hor1,"The Internet","The Internet was invented in the late 1960s by the US Defense Department's Advanced Research Projects Agency. In 1969, there was a network of just four mainframe computers. A mainframe computer is a large, powerful computer, shared by many users. The idea of the electronic mailbox was born when users looked for a way to talk to each other electronically. By 1984,the Internet had begun to develop into the form we know today. Electronic mail is much faster than traditional mail, because once the message is typed out, it arrives in the electronic mail box of the recipient within minutes. It's better to use e-mail to contact friends rather than phone them, because e-mail is cheaper for long distances than the phone. People can share their interests through the Internet and it makes it very easy to exchange ideas and information.\n" +
            "\n" +
            "The fax machine is a very convenient aid to contact companies and friends because messages are transmitted immediately. Fax machines work like photocopiers. They make a copy of a document and then send it down a telephone line to another fax machine. In this  way they can send and receive information from each other. You can send any kind of thigs by fax, but it is more expensive than e-mail."),
    notif(R.drawable.hor4,"Queen Elizabeth II","Since 1066 there have been forty monarchs in England, thirty-five kings, five queens and seven dynasties. Only fourteen monarchs have stayed on the throne for more than twenty-five years, one of them is Queen Elizabeth II.\n" +
            "\n" +
            "Every royal house or 'dynasty' has a surname. In Britain's case that name is Windsor Queen Elizabeth II is the fourth Windsor monarch. She is also the head of a very large family. She has three sons, one daughter, and many grandsons and granddaughters.\n" +
            "\n" +
            "The most famous British royal home is Buckingham Palace. But it is not the only one. The Queen and her family have several other castles, official residences and country houses too. Today Buckingham Palace is the best known palace in the world. It stands at the end of a long boulevard called The Mall and it has 600 rooms on three floors, 400 staff, and 300 clocks.\n" +
            "\n" +
            "After Queen Elizabeth II, Britain's next monarch will probably be Prince Charles, the Prince of Wales. He will be King Charles III. Even further in the future his son, Prince William, will become king too. His title will be King William V. The National Anthem is called 'God save the Queen'. But if Prince Charles becomes King, it will be 'God save the King'.")
)}
